server:
  # 端口
  port: 8081
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  mail:
    host: smtp.qq.com
    username: 840950403@qq.com
    password: fvmsomhjcnxubfid
    stmp:
      socketFactoryClass: javax.net.ssl.SSLSocketFactory
    properties.mail.smtp.port: 465
    from: 840950403@qq.com
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
    # protocol: stmp

  rabbitmq:
    host: 192.168.10.100
    port: 5672
    username: guest
    password: guest
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 100



  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hmsystem?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      # 连接池名
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 最大连接数，默认10
      maximum-pool-size: 10
      # 从连接池返回的连接的自动提交
      auto-commit: true
      # 连接最大存活时间，0表示永久存活，默认1800000（30分钟）
      max-lifetime: 1800000
      # 连接超时时间，默认30000（30秒）
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1


      ## QQ邮箱配置
# Mybatis-plus配置
mybatis-plus:
  #配置Mapper映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置MyBatis数据返回类型别名（默认别名是类名）
  type-aliases-package: org.hmsystem.server.pojo
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: false

jwt:
    #jwt存储的请求头
    tokenHeader: Authorization
    #加密使用的密钥
    secret: hmsystem
    #jwt的超时时间
    expiration: 604800
    #jwt负载的开头
    tokenHead: Bearer